repository:
  has_issues: false
  has_wiki: false
  has_projects: false
  has_downloads: true

labels:
  - name: help wanted
    oldname: help-wanted
    color: 0e8a16
  - name: more-information-needed
    color: d93f0b
  - name: bug
    color: b60205
  - name: feature
    color: 1d76db
  - name: good first issue
    color: "5319e7"

branch_protection:
  restrictions: null
  enforce_admins: false
  required_status_checks:
    strict: true
    contexts:
      - "script/cibuild" # GitHub Actions CI workflow
  required_pull_request_reviews:
    require_code_owner_reviews: false
